using CommunityToolkit.Mvvm.ComponentModel;

namespace FishCash.ViewModels;

/// <summary>
/// Base class for all ViewModels providing common IsBusy/Title functionality
/// </summary>
public abstract partial class BaseViewModel : ObservableObject
{
    [ObservableProperty]
    private bool isBusy;

    [ObservableProperty]
    private string title = string.Empty;

    public bool IsNotBusy => !IsBusy;

    /// <summary>
    /// Auto-notify IsNotBusy when IsBusy changes (generated by source generator)
    /// </summary>
    partial void OnIsBusyChanged(bool value)
    {
        OnPropertyChanged(nameof(IsNotBusy));
    }
}
